# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    apt:
      repo: "puppetlabs/apt"
      ref: "6.3.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "5.3.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "4.2.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "5.2.0"
    translate:
      repo: "puppetlabs/translate"
      ref: "2.1.0"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      ref: "1.0.6"
      puppet_version: ">= 6.0.0"
    systemd:
      repo: "camptocamp/systemd"
      ref: "2.9.0"
  repositories:
    provision: 'https://github.com/puppetlabs/provision.git'
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
