# @summary Manages a Kapacitor
#
# @example
#   include kapacitor
class kapacitor (
  String $key_resource = '',
  String $resource = '',
  String $software = 'influxdata',
  Enum['present', 'absent'] $gpg_manage = 'present',
  String $gpg_id = '05CE15085FC09D18E99EFB22684A14CF2582E0C5',
  String $gpg_server = 'eu.pool.sks-keyservers.net',
  String $gpg_source = 'https://repos.influxdata.com/.influxdb.key',

  Enum['present', 'absent'] $repository_manage = 'present',
  String $repos_comment = 'Kapacitor repository',
  String $repos_location = 'https://repos.influxdata.com/ubuntu',
  String $repos_release ='%{::os.distro.codename}',
  String $repos = 'stable',
  Boolean $repos_src = false,
  Boolean $repos_bin = true,
  Enum['1', '0'] $repos_gpgcheck = '1',
  Enum['1', '0'] $repos_enable = '1',
  Boolean $manage_repo = true,

  String $package= 'kapacitor',
  Enum['present', 'absent'] $package_manage= 'present',

  String $group = 'kapacitor',
  Enum['present', 'absent'] $group_manage = 'present',
  Boolean $group_system = true,
  String $user = 'kapacitor',
  Enum['present', 'absent'] $user_manage = 'present',
  Boolean $user_system = true,
  Boolean $user_manage_home = true,
  String $user_home = '/var/lib/',

  String $configuration_path = '/etc/kapacitor',
  Enum['directory', 'absent'] $configuration_path_manage = 'directory',
  String $configuration_file = 'kapacitor.conf',
  Enum['present', 'absent'] $configuration_file_manage = 'present',
  String $configuration_template= 'kapacitor/kapacitor.conf.erb',

  String $service_defaults = '/etc/default/kapacitor',
  Enum['present', 'absent'] $service_defaults_manage = 'present',
  String $service_default_template = 'kapacitor/service-defaults.erb',
  String $service_definition = '/lib/systemd/system/kapacitor.service',
  Enum['present', 'absent'] $service_definition_manage = 'present',
  String $service_definition_template = 'kapacitor/systemd.service.erb',
  String $service_name = 'kapacitor',
  String $service_provider = 'systemd',
  Enum['running', 'absent'] $service_manage = 'running',
  Boolean $service_enable = true,
  Boolean $service_has_status = true,
  Boolean $service_has_restart = true,

  String $hostname = 'localhost',
  String $data_dir = '/var/lib/kapacitor',
  Enum['directory', 'absent'] $data_dir_manage = 'directory',
  Boolean $skip_config_overrides = false,
  String $default_retention_policy = '',
  String $bind_address = ':9092',
  Boolean $log_enabled = true,
  Boolean $write_tracing = false,
  Boolean $pprof_enabled = false,
  Boolean $https_enabled = false,
  String $https_certificate = '/etc/ssl/kapacitor.pem',
  Enum['present', 'absent'] $https_certificate_manage = 'present',
  String $https_private_key = '',
  Boolean $config_override_enabled = true,
  String $logging_file = '/var/log/kapacitor/kapacitor.log',
  Enum['present', 'absent'] $logging_file_manage = 'present',
  String $logging_level = 'INFO',
  Boolean $load_enabled = true,
  String $load_dir = '/etc/kapacitor/load',
  Enum['directory', 'absent'] $load_dir_manage = 'directory',
  String $replay_dir = '/var/lib/kapacitor/replay',
  Enum['directory', 'absent'] $replay_dir_manage = 'directory',
  String $task_dir = '/var/lib/kapacitor/tasks',
  Enum['directory', 'absent'] $task_dir_manage = 'directory',
  String $task_snapshot_interval = '60s',
  String $storage_boltdb = '/var/lib/kapacitor/kapacitor.db',
  Enum['present', 'absent'] $storage_boltdb_manage = 'present',

  Hash $configuration_influxdb = {},
  Hash $configuration_kubernetes = {},
  Hash $configuration_smtp = {},
  Hash $configuration_snmptrap = {},
  Hash $configuration_opsgenie = {},
  Hash $configuration_victorops = {},
  Hash $configuration_pagerduty = {},
  Hash $configuration_pushover = {},
  Hash $configuration_httppost = {},
  Hash $configuration_slack = {},
  Hash $configuration_telegram = {},
  Hash $configuration_hipchat = {},
  Hash $configuration_kafka = {},
  Hash $configuration_alerta = {},
  Hash $configuration_sensu = {},
  Hash $configuration_reporting = {},
  Hash $configuration_stats = {},
  Hash $configuration_udf = {},
  Hash $configuration_talk = {},
  Hash $configuration_mqtt = {},
  Hash $configuration_swarm = {},
  Hash $configuration_collectd = {},
  Hash $configuration_opentsdb = {},
  Hash $configuration_scraper = {},
  Hash $configuration_azure = {},
  Hash $configuration_consul = {},
  Hash $configuration_dns = {},
  Hash $configuration_ec2 = {},
  Hash $configuration_file_discovery = {},
  Hash $configuration_gce = {},
  Hash $configuration_marathon = {},
  Hash $configuration_nerve = {},
  Hash $configuration_serverset = {},
  Hash $configuration_static_discovery = {},
  Hash $configuration_triton = {},

){

  include ::kapacitor::repo
  include ::kapacitor::install
  include ::kapacitor::config
  contain ::kapacitor::service

  Class['kapacitor::repo'] ~> Class['kapacitor::install']
  Class['kapacitor::install'] ~> Class['kapacitor::config', 'kapacitor::service']

}
