# @summary Parameter definiton
#
# @example
#   include kapacitor::params
class kapacitor::params (
  Boolean $manage_repo = true,
  String $package_name = 'kapacitor',
  String $ensure_package = 'present',
  String $repo_location = 'https://repos.influxdata.com/',
  String $repo_type = 'stable',

  String $group = 'kapacitor',
  Enum['present', 'absent'] $group_manage = 'present',
  Boolean $group_system = true,
  String $user = 'kapacitor',
  Enum['present', 'absent'] $user_manage = 'present',
  Boolean $user_system = true,
  Boolean $user_manage_home = true,
  String $user_home = '/var/lib/',

  String $configuration_path = '/etc/kapacitor',
  Enum['directory', 'absent'] $configuration_path_manage = 'directory',
  String $configuration_file = 'kapacitor.conf',
  Enum['present', 'absent'] $configuration_file_manage = 'present',
  String $configuration_template = 'kapacitor/kapacitor.conf.erb',

  String $service_defaults = '/etc/default/kapacitor',
  Enum['present', 'absent'] $service_defaults_manage = 'present',
  String $service_default_template = 'kapacitor/service-defaults.erb',
  String $service_definition = '/lib/systemd/system/kapacitor.service',
  Enum['present', 'absent'] $service_definition_manage = 'present',
  String $service_definition_template = 'kapacitor/systemd.service.erb',
  String $service_name = 'kapacitor',
  String $service_provider = 'systemd',
  Enum['running', 'stopped'] $service_ensure = 'running',
  Boolean $service_enable = true,
  Boolean $service_has_status = true,
  Boolean $service_has_restart = true,
  Boolean $manage_service = true,
  Boolean $notify_service = true,

  Hash $configuration_influxdb = {},
  Hash $configuration_kubernetes = {},
  Hash $configuration_smtp = {},
  Hash $configuration_snmptrap = {},
  Hash $configuration_opsgenie = {},
  Hash $configuration_victorops = {},
  Hash $configuration_pagerduty = {},
  Hash $configuration_pushover = {},
  Hash $configuration_httppost = {},
  Hash $configuration_slack = {},
  Hash $configuration_telegram = {},
  Hash $configuration_hipchat = {},
  Hash $configuration_kafka = {},
  Hash $configuration_alerta = {},
  Hash $configuration_sensu = {},
  Hash $configuration_reporting = {},
  Hash $configuration_stats = {},
  Hash $configuration_udf = {},
  Hash $configuration_talk = {},
  Hash $configuration_mqtt = {},
  Hash $configuration_swarm = {},
  Hash $configuration_collectd = {},
  Hash $configuration_opentsdb = {},
  Hash $configuration_scraper = {},
  Hash $configuration_azure = {},
  Hash $configuration_consul = {},
  Hash $configuration_dns = {},
  Hash $configuration_ec2 = {},
  Hash $configuration_file_discovery = {},
  Hash $configuration_gce = {},
  Hash $configuration_marathon = {},
  Hash $configuration_nerve = {},
  Hash $configuration_serverset = {},
  Hash $configuration_static_discovery = {},
  Hash $configuration_triton = {},
){

}
